services:
  cs2-server-picker:
    image: taker1988/cs2-server-picker:latest
    container_name: cs2-server-picker
    restart: always
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=Europe/Berlin
      - ALLOW_REGIONS=fra # ADJUST HERE: Whitelist (e.g., fra). Blocks everything else if set.
      - BLOCK_REGIONS=ams,atl,dfw,dxb,eze,gru,gum,hkg,iad,jnb,lax,lhr,lim,mad,ord,par,scl,sea,seo,sgp,sto,syd,tyo,vie,waw,bom2,maa2,sto2,ctum,pekm,pvgm,tgdm,ctut,pekt,pvgt,tgdt,ctuu,peku,pvgu,tgdu # ADJUST HERE: Blacklist. Only active if ALLOW_REGIONS is empty.
    volumes:
      - /volume2/docker_nvme/cs2-server-picker/html:/app/html # ADJUST HERE: Local host path for the generated text files
    ports:
      - "8115:8000" # ADJUST HERE: External port
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8000/blocklist.txt"]
      interval: 1m
      timeout: 10s
      retries: 3
